<a href="https://colab.research.google.com/github/1fac/Archivos-DA/blob/main/Mi_proyecto_61680.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Presentación del proyecto

Este proyecto utiliza técnicas de machine learning para analizar patrones en la facturación y detectar oportunidades de mejora en los beneficios operativos. El enfoque principal es evaluar las diferencias entre la facturación dirigida a sociedades relacionadas y a clientes externos, identificando posibles estrategias para maximizar la rentabilidad. A través de un modelo predictivo, se pretende priorizar la facturación a sociedades externas al grupo, siempre que estas representen una oportunidad financiera más rentable. Los datos analizados incluyen transacciones de sociedades ubicadas en América Latina e Italia. Los resultados esperados incluyen la identificación de nuevos mercados más rentables y un impacto positivo en la estructura operativa.

La motivación de este proyecto radica en la necesidad de optimizar los beneficios operativos y explorar nuevas oportunidades comerciales más rentables fuera del grupo empresarial. Profesionalmente, este trabajo representa una oportunidad clave para destacar en mi rol como asesor financiero, aportando valor estratégico a la organización y fortaleciendo mi desarrollo personal y prestigio dentro de la empresa.


El análisis está dirigido a la dirección y líderes estratégicos de la compañía interesados en optimizar la rentabilidad operativa. También será relevante para equipos de finanzas y planeamiento, dado que el proyecto proporcionará herramientas prácticas para orientar decisiones comerciales basadas en datos.

Conclusión y relevancia

El proyecto busca redefinir la estrategia de facturación al priorizar mercados externos más rentables, lo cual no solo incrementará los beneficios operativos, sino que también diversificará las fuentes de ingreso. La aplicación de machine learning asegura decisiones basadas en datos concretos, maximizando el retorno de inversión y mejorando la eficiencia en la asignación de recursos. Este enfoque representa un cambio estratégico que podría sentar las bases para un crecimiento sostenido en nuevos mercados clave.

En el negocio de ingeniería y construcción, gran parte de la facturación actual se realiza hacia sociedades relacionadas dentro del grupo. Si bien estas transacciones son importantes, podrían estar limitando el potencial de crecimiento de los beneficios operativos. Este proyecto busca evaluar si enfocar una mayor proporción de la facturación hacia sociedades externas al grupo podría generar mejores resultados financieros.

El análisis se centrará exclusivamente en los datos de facturación, sin considerar costos, para identificar patrones y tendencias que ayuden a determinar qué tipo de clientes o mercados generan mayores ingresos. Con el uso de machine learning, se procesará la información histórica de facturación para comparar los ingresos provenientes de sociedades relacionadas frente a los de clientes externos.

El objetivo es sacar conclusiones basadas en datos sobre qué mercados o tipos de clientes ofrecen mejores oportunidades de rentabilidad, especialmente en regiones clave como América Latina e Italia. Esto permitirá a la dirección evaluar opciones para diversificar los ingresos y maximizar los beneficios operativos sin comprometer la estabilidad actual del negocio.

# Presentación ejecutiva

# Lectura de datos

Importo las librerías a utilizar para la lectura, limpieza y procesamiento de datos

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import chardet
import shutil
import requests
from io import StringIO
import locale
import datetime as dt
from datetime import datetime as dt_dt
pd.set_option('display.max_columns', 30)
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

##En este punto accedo a bases relacionales desde Pandas.

Cómo primer punto estoy configurando mí usuario.

In [ ]:
!git config --global user.name "1fac"
!git config --global user.email "facundoseoane@hotmail.com"

Acá estoy clonando la carpeta desde dónde extraígo los datos.

In [ ]:
!git clone https://github.com/1fac/mi_proyecto_git_61680.git

fatal: destination path 'mi_proyecto_git_61680' already exists and is not an empty directory.

Hago una lectura de los archivos que tengo en la carpeta de trabajo.

In [ ]:
!ls mi_proyecto_git_61680

'clase doc.csv'  'df Fac3.csv'	'df Fac6.csv'		   README.md
'df Fac1.csv'	 'df Fac4.csv'	'df Fac7.csv'		   Sociedades.csv
'df Fac2.csv'	 'df Fac5.csv'	 Mi_proyecto_61680.ipynb

Hago una lectura previa para determinar la codificación de los datos

In [ ]:
with open("mi_proyecto_git_61680/df Fac7.csv", "rb") as f:
    result = chardet.detect(f.read())
    print(result)

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

Realizo una lectura previa de uno de los archivos

In [ ]:
with open("mi_proyecto_git_61680/df Fac7.csv", "r", encoding="UTF-8-SIG") as file:
    for i in range(5):
        print(file.readline())

St;Soc.;Div.;Cliente;SocGLA;Nombre Clientes;Clase;Referencia;Nº doc.;Texto;Usuario;Doc.comp.;Ref.fact.;Año;Ejerc./mes;Cuenta;Período;Factura;Lib.mayor;Cta.CP;Venc.neto;Status;Distr;AC;Rg;Material;IR;Fecha doc.;Importe en MD;Mon.;Tp.camb.ef.;Importe en ML;ML;Impte.valor.ML2;Venc.neto;Demora;Compens.;Importe en ML2;ML2;ImpRetImp;ImpteExentRetImpto;Impte.base retenc.;Fe.valor;Fecha pago;MonPa;Importe en MP;Registrado;Soc. Relacionada

@5B\Qcompens.@;PE02;CE04;440;;G Y M ;DZ;COBRANZA GYM;12000031;;OCPPAF;12000031;12000031;2011;2011/02;440;02;;1114119001;440;;;;;;;;12/08/2011;31.715,48;USD;2,745;87.059,00;PEN;31.808,18;12/08/2011;0;12/08/2011;31.808,18;USD;0;0;0;;12/08/2011;;0;15/08/2011;No

@5B\Qcompens.@;PE02;CE04;440;;G Y M ;DZ;COBRANZA GYM;12000031;;OCPPAF;12000031;12000031;2011;2011/02;440;02;;1114119001;9110000006;;;;;;;;12/08/2011;-264.296,03;USD;2,745;-725.492,60;PEN;-264.296,03;12/08/2011;0;12/08/2011;-264.296,03;USD;0;0;0;;12/08/2011;;0;15/08/2011;No

@5B\Qcompens.@;PE02;0140;440;;G Y M ;DZ;;12000043;;TPEJED;12000043;12000043;2004;2004/11;440;11;;1114081001;9110000006;;;;;;;;16/05/2005;-13.985,76;USD;3,26148;-45.614,30;PEN;-13.985,76;16/05/2005;0;16/05/2005;-13.985,76;USD;0;0;0;;16/05/2005;;0;16/05/2005;No

@5B\Qcompens.@;PE02;0140;440;;G Y M ;DZ;;12000044;;TPEJED;12000044;12000044;2004;2004/11;440;11;;1114081001;9110000006;;;;;;;;17/05/2005;-6.220,28;USD;3,48401;-21.671,50;PEN;-6.220,28;17/05/2005;0;17/05/2005;-6.220,28;USD;0;0;0;;17/05/2005;;0;17/05/2005;No

Importo los 7 archivos de datos que confecciona la base total a analizar desde Github y armo un solo Dataset

In [ ]:
# URLs de los archivos en GitHub
urls = [
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac1.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac2.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac3.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac4.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac5.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac6.csv",
    "https://raw.githubusercontent.com/1fac/mi_proyecto_git_61680/main/df%20Fac7.csv",
]

# Lista para almacenar los DataFrames
dataframes = []

# Descargar y cargar cada archivo en un DataFrame
for url in urls:
    response = requests.get(url)
    if response.status_code == 200:
        csv_data = StringIO(response.text)
        df = pd.read_csv(csv_data, sep=";", encoding="UTF-8-SIG", low_memory=False)
        dataframes.append(df)
    else:
        print(f"Error al descargar el archivo: {url}")

# Combinar todos los DataFrames en uno solo
df_comp_orig = pd.concat(dataframes, ignore_index=True)

# Mostrar las primeras filas del dataset combinado
print(df_comp_orig.head(5))
print(f"Total de filas combinadas: {len(df_comp_orig)}")

               St  Soc.  Div. Cliente  SocGLA  \
0  @5B\Qcompens.@  01CA  KZ38     227  S00133
1  @5B\Qcompens.@  01CA  KZ38     227  S00133
2  @5B\Qcompens.@  01CA  KZ38     227  S00133
3  @5B\Qcompens.@  01CA  KZ38     227  S00133
4  @5B\Qcompens.@  01CA  KZ38     227  S00133

                    Nombre Clientes Clase Referencia     Nº doc. Texto  \
0  Ingenieria y Construcción CHILE     DZ        NaN  12000011.0   NaN
1  Ingenieria y Construcción CHILE     DZ        NaN  12000012.0   NaN
2  Ingenieria y Construcción CHILE     DZ        NaN  12000014.0   NaN
3  Ingenieria y Construcción CHILE     DZ        NaN  12000020.0   NaN
4  Ingenieria y Construcción CHILE     DZ        NaN  12000027.0   NaN

  Usuario   Doc.comp. Ref.fact.     Año Ejerc./mes  ... Impte.valor.ML2  \
0  TEAIRL  12000011.0  12000011  2010.0    2010/05  ...      547.065,59
1  TEAIRL  12000014.0  12000012  2010.0    2010/05  ...     -547.065,59
2  TEAIRL  12000014.0  12000014  2010.0    2010/06  ...     -415.303,68
3  TEAIRL  12000020.0  12000020  2010.0    2010/11  ...     -202.596,03
4  TEAIRL  12000027.0  12000027  2009.0    2009/12  ...      -16.141,50

   Venc.neto.1  Demora    Compens. Importe en ML2  ML2  ImpRetImp  \
0   30/11/2010     0.0  30/11/2010     547.065,59  USD        0.0
1   30/11/2010    29.0  29/12/2010    -547.065,59  USD        0.0
2   29/12/2010     0.0  29/12/2010    -415.303,68  USD        0.0
3   18/05/2011     0.0  18/05/2011    -202.596,03  USD        0.0
4   07/06/2010     0.0  07/06/2010     -16.141,50  USD        0.0

   ImpteExentRetImpto  Impte.base retenc.  Fe.valor  Fecha pago MonPa  \
0                 0.0                 0.0       NaN  30/11/2010   NaN
1                 0.0                 0.0       NaN  30/11/2010   NaN
2                 0.0                 0.0       NaN  29/12/2010   NaN
3                 0.0                 0.0       NaN  18/05/2011   NaN
4                 0.0                 0.0       NaN  07/06/2010   NaN

  Importe en MP  Registrado Soc. Relacionada
0           0.0  08/12/2010               Si
1           0.0  08/12/2010               Si
2           0.0  06/01/2011               Si
3           0.0  08/06/2011               Si
4           0.0  14/06/2010               Si

[5 rows x 48 columns]
Total de filas combinadas: 436866

Guardo como CSV el dataset confeccionado.

In [ ]:
df_comp_orig.to_csv("df_comp_orig.csv", index=False, sep=";", encoding="UTF-8-SIG")

Muevo el archivo al repositorio de Github clonado.

In [ ]:
!mv ../df_comp_orig.csv .

# Data Wranglimg - Limpieza y transformación de datos

Realizo una consulta de las columnas que tiene y confecciono un diccionario para entender los datos a analizar.

In [ ]:
df_comp_orig.columns

Index(['St', 'Soc.', 'Div.', 'Cliente', 'SocGLA', 'Nombre Clientes', 'Clase',
       'Referencia', 'Nº doc.', 'Texto', 'Usuario', 'Doc.comp.', 'Ref.fact.',
       'Año', 'Ejerc./mes', 'Cuenta', 'Período', 'Factura', 'Lib.mayor',
       'Cta.CP', 'Venc.neto', 'Status', 'Distr', 'AC', 'Rg', 'Material', 'IR',
       'Fecha doc.', 'Importe en MD', 'Mon.', 'Tp.camb.ef.', 'Importe en ML',
       'ML', 'Impte.valor.ML2', 'Venc.neto.1', 'Demora', 'Compens.',
       'Importe en ML2', 'ML2', 'ImpRetImp', 'ImpteExentRetImpto',
       'Impte.base retenc.', 'Fe.valor', 'Fecha pago', 'MonPa',
       'Importe en MP', 'Registrado', 'Soc. Relacionada'],
      dtype='object')

###Diccionario del Dataset

St: Estado del Documento

Soc.: Sociedad Emisora

Div.: Nomenclador de proyecto por sociedad

Cliente: N° de Cliente

SocGLA: Código de sociedad relacionada

Nombre Clientes: Nombre de cliente

Clase: Nomenclador del tipo de comprobante emitido

Referencia: Número de documento

Nº doc.: Número de documento interno

Texto: Texto de referencia

Usuario: Usuario que registro al sistema

Doc.comp.: Documento interno que referencia operaciones

Ref.fact.: Número de documento interno o asociación a documentos

Año: Año de ejercicio

Ejerc./mes: Año y mes de ejercicio

Cuenta: N° de Cliente

Período: Período de ejercicio

Factura: Dato no relevante

Lib.mayor: Cuenta contable contrapartida

Cta.CP: Cuenta contable

Venc.neto: Vencimiento del pago

Status: Sin datos

Distr: Sin datos

AC: Sin datos

Rg: Sin datos

Material: Sin datos

IR: No relevante

Fecha doc.: Fecha de documento

Importe en MD: Importe en moneda de documento

Mon.: Moneda de documento

Tp.camb.ef.: Tipo de cambios de moneda extranjera con respecto a moneda local

Importe en ML: Importe en moneda local

ML: Moneda local

Impte.valor.ML2: No relevante

Venc.neto.1: No relevante

Demora: Días de vencimiento

Compens.: Fecha de compensación

Importe en ML2: Importe en dolares

ML2: Moneda dólar

ImpRetImp: Importe retenido de impuestos

ImpteExentRetImpto: Importe exento de retencion

Impte.base retenc.: Base de retención

Fe.valor: No relevante

Fecha pago: Fecha de Pago


MonPa: No relevante

Importe en MP: No relevante

Registrado: Fecha de registro del documento

Soc. Relacionada: La sociedad es relacionada o no

Identificar valores nulos

In [ ]:
df_comp_orig.isnull().sum()

St                     10161
Soc.                   10161
Div.                   10161
Cliente                10161
SocGLA                258274
Nombre Clientes        10171
Clase                  10161
Referencia             46113
Nº doc.                10161
Texto                  87747
Usuario                10161
Doc.comp.              13499
Ref.fact.              10161
Año                    10161
Ejerc./mes             10161
Cuenta                 10161
Período                10161
Factura               406001
Lib.mayor              10161
Cta.CP                 10161
Venc.neto             205723
Status                436866
Distr                 436866
AC                    436866
Rg                    436866
Material              436866
IR                    410360
Fecha doc.             10161
Importe en MD          10161
Mon.                   10161
Tp.camb.ef.            11727
Importe en ML          10161
ML                     10161
Impte.valor.ML2        10161
Venc.neto.1            10161
Demora                 10161
Compens.               13499
Importe en ML2         10161
ML2                    10161
ImpRetImp              10161
ImpteExentRetImpto     10161
Impte.base retenc.     10161
Fe.valor              436866
Fecha pago             10161
MonPa                 436866
Importe en MP          10161
Registrado             10161
Soc. Relacionada       10161
dtype: int64

Según se observa, hay filas completas que tienen datos irrelevantes, y apuntan a ser 10.161 registros.

Elimino las columnas que no me parecen relevantes a priori

In [ ]:
dropna_columns =['St', 'Cuenta', 'Factura', 'Lib.mayor', 'Cta.CP', 'Venc.neto', 'Status', 'Distr', 'AC', 'Rg', 'Material', 'IR', 'Impte.valor.ML2', 'Venc.neto.1', 'Impte.base retenc.', 'Fe.valor', 'MonPa', 'Importe en MP','ImpRetImp', 'ImpteExentRetImpto', 'Impte.base retenc.']
df_comp_orig.drop(columns=dropna_columns, inplace=True)

In [ ]:
df_comp_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436866 entries, 0 to 436865
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Soc.              426705 non-null  object
 1   Div.              426705 non-null  object
 2   Cliente           426705 non-null  object
 3   SocGLA            178592 non-null  object
 4   Nombre Clientes   426695 non-null  object
 5   Clase             426705 non-null  object
 6   Referencia        390753 non-null  object
 7   Nº doc.           426705 non-null  float64
 8   Texto             349119 non-null  object
 9   Usuario           426705 non-null  object
 10  Doc.comp.         423367 non-null  float64
 11  Ref.fact.         426705 non-null  object
 12  Año               426705 non-null  float64
 13  Ejerc./mes        426705 non-null  object
 14  Período           426705 non-null  float64
 15  Fecha doc.        426705 non-null  object
 16  Importe en MD     426705 non-null  object
 17  Mon.              426705 non-null  object
 18  Tp.camb.ef.       425139 non-null  object
 19  Importe en ML     426705 non-null  object
 20  ML                426705 non-null  object
 21  Demora            426705 non-null  float64
 22  Compens.          423367 non-null  object
 23  Importe en ML2    426705 non-null  object
 24  ML2               426705 non-null  object
 25  Fecha pago        426705 non-null  object
 26  Registrado        426705 non-null  object
 27  Soc. Relacionada  426705 non-null  object
dtypes: float64(5), object(23)
memory usage: 93.3+ MB

Tomo una muestra aleatoria de 10 filas

In [ ]:
df_comp_orig.sample(10)

,Soc.,Div.,Cliente,SocGLA,Nombre Clientes,Clase,Referencia,Nº doc.,Texto,Usuario,Doc.comp.,Ref.fact.,Año,Ejerc./mes,Período,Fecha doc.,Importe en MD,Mon.,Tp.camb.ef.,Importe en ML,ML,Demora,Compens.,Importe en ML2,ML2,Fecha pago,Registrado,Soc. Relacionada
404196,VE13,0054,475,S00195,Sidor C.A.,DR,4659/4659,11000033.0,Serv. Reparación Discos Peletizadores .Adicion...,COTARI,12000031.0,11000033,2007.0,2007/08,8.0,15/02/2008,"20.148,29",VEF,1,"20.148,29",VEF,45.0,30/04/2008,"9.371,38",USD,16/03/2008,15/02/2008,Si
124226,BR05,TEPA,10025,NaN,Emerson Martins De Andrade,AB,NaN,30031466.0,COD: 010025 EMERSON MARTINS DE A REF:,TBRDRA,30031466.0,30031466,2021.0,2021/09,9.0,30/03/2022,"-13.250,00",BRL,1,"-13.250,00",BRL,0.0,30/03/2022,"-2.514,32",USD,30/03/2022,30/03/2022,No
48554,AR02,0348,3361,NaN,BLOQUE PETROLERO SAN ANTONIO,DZ,FCS SABALO,12001738.0,NaN,TEACGL,90000022.0,10006935,2011.0,2011/06,6.0,21/12/2011,"38.588,07",ARS,1,"38.588,07",ARS,9.0,30/12/2011,"9.032,79",USD,21/12/2011,03/01/2012,No
81895,AR31,0386,1168,NaN,GOBIERNO DE LA CIUDAD DE BUENOS AIR,DZ,COBR FCB 3-1657,12000133.0,COBR FCB 3-1657,TEADEJ,12000133.0,12000133,2017.0,2017/04,4.0,17/10/2017,"-5.165.965,62",ARS,1,"-5.165.965,62",ARS,0.0,17/10/2017,"-299.626,01",USD,17/10/2017,18/10/2017,No
236444,AR02,TE01,119,NaN,YPF,DB,0070A00006165,11001174.0,Servicios de Ingeniería Nov’18,TEALDB,12001138.0,11001174,2018.0,2018/07,7.0,09/01/2019,"232.027,59",ARS,1,"232.027,59",ARS,6.0,14/02/2019,"6.171,94",USD,08/02/2019,09/01/2019,No
336607,AR16,Z222,688,NaN,TELMEX ARGENTINA,DB,0022A00000162,11000114.0,OC.4400003178 - OBRAS CAPEX FO AMBA,TSRAIS,30000550.0,11000114,2014.0,2014/02,2.0,22/08/2014,"97.472,33",ARS,1,"97.472,33",ARS,-10.0,11/09/2014,"11.608,95",USD,21/09/2014,22/08/2014,No
395928,UY09,0391,4316,NaN,ZONA FRANCA PUNTA PEREIRA,DZ,RECLAS. A FR,12000154.0,Reclasificación a FR s/mail Dumrauf 05/11/13,TURMMA,30000050.0,12000154,2013.0,2013/04,4.0,31/10/2013,"-10.367,21",USD,"21,504","-222.936,48",UYU,974.0,01/07/2016,"-10.367,21",USD,31/10/2013,08/11/2013,No
219775,AR02,0521,54,S00077,Petroleos,DB,0070A00011259,11000156.0,Obras Complementarias - NP 4650000075 - FDP ...,TEASKV,12000111.0,11000156,2022.0,2022/01,1.0,29/07/2022,"43.737,02",USD,"131,12","5.734.798,06",ARS,1.0,29/08/2022,"43.737,02",USD,28/08/2022,02/08/2022,Si
63532,AR05,0050,104,S00040,Aceros ARGENTINA,DZ,DOC 11000303,12000292.0,NaN,TEADOM,12000292.0,12000292,2005.0,2005/11,11.0,23/05/2006,"-857.554,25",ARS,1,"-857.554,25",ARS,0.0,23/05/2006,"-281.874,88",USD,23/05/2006,30/05/2006,Si
431360,UY07,GG09,287,S00096,Ingenieria y Construcción INTERNATIONAL CONSTR...,DR,001501,11000223.0,REEMBOLSO DE GASTOS EFECTUADOS POR VUESTRA CUENTA,BAIGRC,30000392.0,11000223,2012.0,2012/09,9.0,22/03/2013,"4.722,65",USD,"19,004","89.749,24",UYU,94.0,24/06/2013,"4.722,65",USD,22/03/2013,25/03/2013,Si

Observo valores Nan

In [ ]:
nan_rows = df_comp_orig.iloc[365756:375916]

In [ ]:
nan_rows.sample(10)

,Soc.,Div.,Cliente,SocGLA,Nombre Clientes,Clase,Referencia,Nº doc.,Texto,Usuario,Doc.comp.,Ref.fact.,Año,Ejerc./mes,Período,Fecha doc.,Importe en MD,Mon.,Tp.camb.ef.,Importe en ML,ML,Demora,Compens.,Importe en ML2,ML2,Fecha pago,Registrado,Soc. Relacionada
371850,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
374858,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
369984,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
371060,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
371181,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
366375,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
372197,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375054,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
370430,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
366288,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nan_rows.head(10)

,Soc.,Div.,Cliente,SocGLA,Nombre Clientes,Clase,Referencia,Nº doc.,Texto,Usuario,Doc.comp.,Ref.fact.,Año,Ejerc./mes,Período,Fecha doc.,Importe en MD,Mon.,Tp.camb.ef.,Importe en ML,ML,Demora,Compens.,Importe en ML2,ML2,Fecha pago,Registrado,Soc. Relacionada
365756,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365757,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365758,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365759,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365760,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365761,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365762,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365763,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365764,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
365765,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nan_rows.tail(10)

,Soc.,Div.,Cliente,SocGLA,Nombre Clientes,Clase,Referencia,Nº doc.,Texto,Usuario,Doc.comp.,Ref.fact.,Año,Ejerc./mes,Período,Fecha doc.,Importe en MD,Mon.,Tp.camb.ef.,Importe en ML,ML,Demora,Compens.,Importe en ML2,ML2,Fecha pago,Registrado,Soc. Relacionada
375906,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375907,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375908,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375909,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375910,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375911,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375912,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375913,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375914,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
375915,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

Le doy formato a algunos campos objects

In [ ]:
df_comp_orig['Período'] = pd.to_numeric(df_comp_orig['Período'], errors='coerce').fillna(0).astype(int)

In [ ]:
df_comp_orig['Año'] = pd.to_numeric(df_comp_orig['Año'], errors='coerce').fillna(0).astype(int)

In [ ]:
df_comp_orig['Demora'] = pd.to_numeric(df_comp_orig['Demora'], errors='coerce').fillna(0).astype(int)

In [ ]:
df_comp_orig['SocGLA'] = df_comp_orig['SocGLA'].astype('string')

In [ ]:
df_comp_orig['Referencia'] = df_comp_orig['Referencia'].astype('string')

In [ ]:
df_comp_orig['Nº doc.'] = pd.to_numeric(df_comp_orig['Nº doc.'], errors='coerce').fillna(0).astype(int)

In [ ]:
df_comp_orig['Doc.comp.'] = pd.to_numeric(df_comp_orig['Doc.comp.'], errors='coerce').fillna(0).astype(int)

In [ ]:
df_comp_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436866 entries, 0 to 436865
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Soc.              426705 non-null  object
 1   Div.              426705 non-null  object
 2   Cliente           426705 non-null  object
 3   SocGLA            178592 non-null  string
 4   Nombre Clientes   426695 non-null  object
 5   Clase             426705 non-null  object
 6   Referencia        390753 non-null  string
 7   Nº doc.           436866 non-null  int64
 8   Texto             349119 non-null  object
 9   Usuario           426705 non-null  object
 10  Doc.comp.         436866 non-null  int64
 11  Ref.fact.         426705 non-null  object
 12  Año               436866 non-null  int64
 13  Ejerc./mes        426705 non-null  object
 14  Período           436866 non-null  int64
 15  Fecha doc.        426705 non-null  object
 16  Importe en MD     426705 non-null  object
 17  Mon.              426705 non-null  object
 18  Tp.camb.ef.       425139 non-null  object
 19  Importe en ML     426705 non-null  object
 20  ML                426705 non-null  object
 21  Demora            436866 non-null  int64
 22  Compens.          423367 non-null  object
 23  Importe en ML2    426705 non-null  object
 24  ML2               426705 non-null  object
 25  Fecha pago        426705 non-null  object
 26  Registrado        426705 non-null  object
 27  Soc. Relacionada  426705 non-null  object
dtypes: int64(5), object(21), string(2)
memory usage: 93.3+ MB

# Análisis Exploratorio de datos

In [ ]:
df_comp_orig.sample(10)

,Soc.,Div.,Cliente,SocGLA,Nombre Clientes,Clase,Referencia,Nº doc.,Texto,Usuario,Doc.comp.,Ref.fact.,Año,Ejerc./mes,Período,Fecha doc.,Importe en MD,Mon.,Tp.camb.ef.,Importe en ML,ML,Demora,Compens.,Importe en ML2,ML2,Fecha pago,Registrado,Soc. Relacionada
136999,BR12,0519,9670,<NA>,Piranga Peças E Equipamentos Usados,DR,000001061-1,11000052,COD: 009670 PIRANGA PEÇAS E EQUI REF: 0090110161,TBRUKQ,30001091,11000052,2024,2024/01,1,22/07/2024,"1.900,00",BRL,1,"1.900,00",BRL,1,23/07/2024,"342,08",USD,22/07/2024,22/07/2024,No
42766,AR02,CO01,378,<NA>,Deudor por Cobranzas varias Sta Mar,TJ,<NA>,1117000272,NaN,TEAKUT,1117000272,1117000272,2011,2011/03,3,02/09/2011,"-27.754,71",USD,"4,204","-116.680,80",ARS,0,02/09/2011,"-27.754,71",USD,02/09/2011,07/09/2011,No
96647,BR03,0290,1766,<NA>,PETROLEO BRASILEIRO S A PETROBRAS,DZ,11000661,12000353,RECEBIMENTO PETROBRAS - NF 01866 RPBC SOC,TBRECF,12000353,12000353,2009,2009/06,6,24/12/2009,"-333,2",BRL,1,"-333,2",BRL,0,24/12/2009,"-191,98",USD,24/12/2009,30/12/2009,No
143069,BS02,TEPA,LBR05,<NA>,Cliente Interno Liquidación BR05,ET,0090027779,49000000,NaN,TEASJW,81000006,V,2011,2011/01,1,20/07/2011,"-18.096,00",USD,1,"-18.096,00",USD,2,30/11/2018,"-18.096,00",USD,20/07/2011,26/07/2011,No
230927,AR02,0050,104,S00040,Aceros ARGENTINA,DB,0056A00003750,11001245,Certificado correspondiente a Febrero-14,TEATJM,12001082,11001245,2013,2013/08,8,28/02/2014,"44.636,35",ARS,1,"44.636,35",ARS,-4,26/03/2014,"5.704,53",USD,30/03/2014,05/03/2014,Si
12010,02MX,M351,278,S00129,Ingenieria y Construcción DE,DZ,"A-594,95,98,99",12000034,"A-594,95,98,99",TMXHNZ,12000034,12000034,2016,2016/10,10,25/04/2017,"-16.389,19",MXN,1,"-16.389,19",MXN,0,25/04/2017,"-823,07",USD,25/04/2017,02/05/2017,Si
124352,BR05,0499,10059,<NA>,CHACARA DO THOME FESTAS E EVENTOS E,DR,000001190-1,11000280,COD: 010059 CHACARA DO THOME FES REF: 0090098720,TBRNRO,12000326,11000280,2021,2021/08,8,15/02/2022,500,BRL,1,500,BRL,71,27/04/2022,"95,96",USD,15/02/2022,15/02/2022,No
3257,01MX,MZ61,2104,S01041,TANKS TECHNOLOGIES,XD,RECLA CARGA INIC,90000103,10105002001002-SUBSIDIARIAS CTA. CTE. ME (A),TMXRCK,90000103,90000103,2007,2007/12,12,31/12/2007,"-100.625,00",USD,"10,8662","-1.093.411,38",MXN,182,30/06/2008,"-100.625,00",USD,31/12/2007,10/07/2008,Si
427940,UY05,0351,3381,<NA>,OSE,DR,033811,11000103,CERTIFICADO BASICO No 3 - DIC/2010 - LIC 1411,TURPER,12000231,11000103,2010,2010/06,6,23/12/2010,"446.880,00",UYU,1,"446.880,00",UYU,-29,31/01/2011,"22.359,65",USD,01/03/2011,27/12/2010,No
19918,03MX,M331,278,S00129,Ingenieria y Construcción DE,DZ,"FCS.A54,60 TECHI",12000095,"FCs.A54,60 Ingenieria y COnstrucción",TMXOEO,12000095,12000095,2010,2010/12,12,30/06/2011,"-131.646,80",MXN,1,"-131.646,80",MXN,0,30/06/2011,"-11.361,79",USD,30/06/2011,04/07/2011,Si

# Preprocesamiento de datos

# Feature Selection

# Modelos

# Optimización de modelos

# Conclusiones Finales

In [ ]:
# prompt: quiero armar una tabla para ver la SocGLA de cada cliente

# ... (Your existing code)

# Assuming 'df_comp_orig' is your combined DataFrame

# Create the table for SocGLA by client
socgla_table = df_comp_orig.groupby('Cliente')['SocGLA'].unique().reset_index()

# Display the table
socgla_table

# ... (Rest of your code)

     Cliente  SocGLA
0        100  [<NA>]
1      10001  [<NA>]
2      10002  [<NA>]
3      10003  [<NA>]
4      10004  [<NA>]
...      ...     ...
8001   LUY04  [<NA>]
8002   LUY05  [<NA>]
8003   LUY07  [<NA>]
8004   LVE03  [<NA>]
8005   LVE04  [<NA>]

[8006 rows x 2 columns]

In [ ]:
socgla_table = df_comp_orig.groupby('SocGLA')['Cliente'].unique().reset_index()

In [ ]:
socgla_table

     SocGLA                   Cliente
0    B1189F  [7501, 6118, 6145, 6131]
1    B1189U        [6118, 6245, 6131]
2    B459BE  [7646, 6300, 7428, 6838]
3    B459EG        [5841, 7416, 8000]
4    B459FR        [6296, 6299, 6747]
..      ...                       ...
273  Z01009        [1228, 4915, 6139]
274  Z01011                    [6033]
275  Z01018                    [6037]
276  Z01023                    [6091]
277  Z01028                    [6034]

[278 rows x 2 columns]

In [ ]:
df = pd.read_csv('df_comp_orig.csv', na_values=['', 'NA', 'nan'], sep=',')

ParserError: Error tokenizing data. C error: Expected 5 fields in line 3, saw 6